### ISSUE TITLE
Improve Hypixel checks

### ISSUE THREAD

**Issue by scorpion3013** [scorpion3013/minecraft-account-recovery-tool#11]

**Comment by memesarecool** [comment]
Pushed this

**Comment by scorpion3013** [comment]
Starting to replace the current hypixel checks with a new api based one. https://api.hypixel.net/

**Comment by scorpion3013** [comment]
Rank check done.
Level check not done.

**Comment by scorpion3013** [comment]
![grafik](https://user-images.githubusercontent.com/27446646/47267098-53c6e600-d53f-11e8-89e9-dde1d51a3fbc.png)
Unable to get the correct level with the functions

**Comment by scorpion3013** [comment]
Found my error, all hypixel checks are now api based

**Comment by scorpion3013** [comment]
I will keep the Hypixel api in it for now cause its much more stable and faster than the other site,
if will later add support for multible api keys via .txt

**Comment by memesarecool** [comment]
> 
> 
> I will keep the Hypixel api in it for now cause its much more stable and faster than the other site,
> if will later add support for multible api keys via .txt

Alright, sounds good. I personally wouldn't use it due to the reasons I listed in my reply on this[https://github.com/scorpion3013/minecraft-account-recovery-tool/issues/8#issuecomment-431683059](url) issue
